class ConvertTimestampToTimestamptz < ActiveRecord::Migration
  def up
    # Generated by:
    # select 'alter table ' || table_name || ' alter column ' || column_name || ' type timestamptz;' 
    # from information_schema.columns
    # where table_schema='public'
    #   and data_type='timestamp without time zone'

    execute <<-END_SQL
      alter table sessions alter column created_at type timestamptz;
      alter table sessions alter column updated_at type timestamptz;
      alter table settings alter column created_at type timestamptz;
      alter table settings alter column updated_at type timestamptz;
      alter table accounts alter column deleted_at type timestamptz;
      alter table accounts alter column created_at type timestamptz;
      alter table accounts alter column updated_at type timestamptz;
      alter table permissions alter column created_at type timestamptz;
      alter table permissions alter column updated_at type timestamptz;
      alter table preferences alter column created_at type timestamptz;
      alter table preferences alter column updated_at type timestamptz;
      alter table campaigns alter column deleted_at type timestamptz;
      alter table campaigns alter column created_at type timestamptz;
      alter table campaigns alter column updated_at type timestamptz;
      alter table account_contacts alter column deleted_at type timestamptz;
      alter table account_contacts alter column created_at type timestamptz;
      alter table account_contacts alter column updated_at type timestamptz;
      alter table account_opportunities alter column deleted_at type timestamptz;
      alter table account_opportunities alter column created_at type timestamptz;
      alter table account_opportunities alter column updated_at type timestamptz;
      alter table contact_opportunities alter column deleted_at type timestamptz;
      alter table contact_opportunities alter column created_at type timestamptz;
      alter table contact_opportunities alter column updated_at type timestamptz;
      alter table activities alter column created_at type timestamptz;
      alter table activities alter column updated_at type timestamptz;
      alter table avatars alter column created_at type timestamptz;
      alter table avatars alter column updated_at type timestamptz;
      alter table addresses alter column created_at type timestamptz;
      alter table addresses alter column updated_at type timestamptz;
      alter table addresses alter column deleted_at type timestamptz;
      alter table contacts alter column deleted_at type timestamptz;
      alter table contacts alter column created_at type timestamptz;
      alter table contacts alter column updated_at type timestamptz;
      alter table users alter column last_request_at type timestamptz;
      alter table users alter column last_login_at type timestamptz;
      alter table users alter column current_login_at type timestamptz;
      alter table users alter column deleted_at type timestamptz;
      alter table users alter column created_at type timestamptz;
      alter table users alter column updated_at type timestamptz;
      alter table users alter column suspended_at type timestamptz;
      alter table opportunities alter column deleted_at type timestamptz;
      alter table opportunities alter column created_at type timestamptz;
      alter table opportunities alter column updated_at type timestamptz;
      alter table tasks alter column due_at type timestamptz;
      alter table tasks alter column completed_at type timestamptz;
      alter table tasks alter column deleted_at type timestamptz;
      alter table tasks alter column created_at type timestamptz;
      alter table tasks alter column updated_at type timestamptz;
      alter table leads alter column deleted_at type timestamptz;
      alter table leads alter column created_at type timestamptz;
      alter table leads alter column updated_at type timestamptz;
      alter table comments alter column created_at type timestamptz;
      alter table comments alter column updated_at type timestamptz;
      alter table emails alter column sent_at type timestamptz;
      alter table emails alter column received_at type timestamptz;
      alter table emails alter column deleted_at type timestamptz;
      alter table emails alter column created_at type timestamptz;
      alter table emails alter column updated_at type timestamptz;
      alter table taggings alter column created_at type timestamptz;
      alter table field_groups alter column created_at type timestamptz;
      alter table field_groups alter column updated_at type timestamptz;
      alter table lists alter column created_at type timestamptz;
      alter table lists alter column updated_at type timestamptz;
      alter table versions alter column created_at type timestamptz;
      alter table groups alter column created_at type timestamptz;
      alter table groups alter column updated_at type timestamptz;
      alter table lead_status_changes alter column created_at type timestamptz;
      alter table fields alter column created_at type timestamptz;
      alter table fields alter column updated_at type timestamptz;
    END_SQL
  end

  def down
    raise IrreversibleMigration
  end
end
